_BASE_: "../PANDA-Base.yml"

INFO:
  UID: 'PANDA-Epoch_5_9'

MODEL:
  ANCHOR:
    INCLUDE_STRATEGY: 'IncludeIgnoreSmall'

SOLVER:
  MAX_EPOCH: 9
  STEPS: [5]

OUTPUT:
  ROOT_DIR: 'outputs/PANDA-Epoch_5_9'