_BASE_: "../PANDA-Base.yml"

INFO:
  UID: 'PANDA-Epoch_5_9-SGD'

MODEL:
  ANCHOR:
    INCLUDE_STRATEGY: 'IncludeIgnoreSmall'

SOLVER:
  OPTIMIZER: 'SGD'
  MAX_EPOCH: 9
  STEPS: [5]

OUTPUT:
  ROOT_DIR: 'outputs/PANDA/Adam/SGD'