_BASE_: "../PANDA-Base.yml"

INFO:
  UID: 'PANDA-Anchor-2_4_8'

MODEL:
  ANCHOR:
    INCLUDE_STRATEGY: 'IncludeIgnoreSmall'
  PGN_ANCHOR_SCALES: [2, 4, 8]

SOLVER:
  MAX_EPOCH: 9
  STEPS: [5]

OUTPUT:
  ROOT_DIR: 'outputs/PANDA/Anchor/2_4_8'